### ISSUE TITLE
Cinder include for xcode

### ISSUE THREAD

**Issue by kfarr** [chaimgingold/Tabla#2]
Sorry for the newb question but I can't seem to get this to compile because I'm not able to find the right place to put the cinder library.

Can you provide a bit more guidance on which dir from the cinder zip should be placed where within the tabla git repo subdirectories to make sure xcode can reference it properly? I've tried a bunch of directories but can't think of any more to put it in.

Looking forward to trying this out!

**Comment by georgetmayorga** [comment]
hey @kfarr—we were having issues, it seems the build depends on cinder 0.9.0 (latest on their site is 0.9.1) so making sure it's 0.9.0 and saving it to sibling directory seems to work
```
-Code
|-Tabla
|-cinder_0.9.0_mac
```

**Comment by kfarr** [comment]
Thanks, yes placing it as a sibling in the same parent directory as Tabla worked for me. Not familiar with xcode library dependencies so surprised that was the proper place to put it. Got it running now trying to calibrate, will let you know if I run into any other problems.
